// apps/vue/src/components/CoinItem.vue
<template>
  <ion-item
    button
    color="primary"
    :detail="false"
    :routerLink="'/coins/' + coin.id"
  >
    <ion-avatar slot="start">
      <ion-img :src="coin.image" :alt="coin.name"></ion-img>
    </ion-avatar>
    <ion-label>
      <h2 class="bold">
        <ion-text color="light">
          {{ coin.name }}
        </ion-text>
      </h2>
    </ion-label>
    <div slot="end">
      <p class="bold">
        {{
          $formatNumber(coin.current_price, {
            style: "currency",
            currency: "USD",
            maximumFractionDigits: 8,
          })
        }}
      </p>
    </div>
  </ion-item>
</template>

<script lang="ts">
import { IonImg, IonAvatar, IonItem, IonText, IonLabel } from "@ionic/vue";
import { CoinModel } from "@/models/CoinModel";
import { PropType } from "vue";

export default {
  name: "CoinItem",
  components: {
    IonImg,
    IonAvatar,
    IonItem,
    IonText,
    IonLabel,
  },
  props: {
    coin: {
      type: Object as PropType<CoinModel>,
      required: true,
    },
  },
  setup() {
    return {};
  },
};
</script>

<style lang="scss" scoped>
ion-item {
  --background: transparent;
}

ion-avatar {
  min-width: 25px !important;
  min-height: 25px !important;
  background: white;
  padding: 2px;
}
</style>

// apps/react/src/components/CoinItem.tsx
import { IonAvatar, IonImg, IonItem, IonLabel, IonText } from '@ionic/react';
import React, { useState } from 'react';
import { FormattedNumber } from 'react-intl';

interface CoinProps {
  id: string;
  name: string;
  price: number;
  image: string;
}

const CoinItem: React.FC<CoinProps> = ({ id, name, image, price }) => {

  const [isImageLoaded, setIsImageLoaded] = useState(false);

  const onImageLoaded = () => {
    setIsImageLoaded(true);
  };

  return (
    <IonItem class="coin-item" button color="primary" detail={false} routerLink={'/coins/' + id}>
      <IonAvatar slot="start" style={{ backgroundColor: 'white', padding: '2px' }}>
        <IonImg className={`${isImageLoaded && 'fade-in'}`} src={image} alt={name} onIonImgDidLoad={onImageLoaded} />
      </IonAvatar>
      <IonLabel>
        <h2 className="bold">
          <IonText color="light">
            {name}
          </IonText>
        </h2>
      </IonLabel>
      <div slot="end">
        <p className="bold">
          <FormattedNumber value={price} style="currency" currency="USD" maximumFractionDigits={8} />
        </p>
      </div>
    </IonItem>
  )
}

export default CoinItem;
