// apps/react/src/components/PostItem.tsx
import { IonImg, IonItem, IonLabel, IonThumbnail } from '@ionic/react';
import React, { useState } from 'react';
import { Browser } from "@capacitor/browser";
import { FormattedDate } from 'react-intl';

interface PostProps {
  title: string;
  image: string;
  source: string;
  published: number;
  url: string;
}

const PostItem: React.FC<PostProps> = ({ title, image, source, published, url }) => {

  const [isImageLoaded, setIsImageLoaded] = useState(false);

  const onImageLoaded = () => {
    setIsImageLoaded(true);
  };

  const openUrl = (url: string) => {
    Browser.open({
      url: url,
      windowName: "_target",
      toolbarColor: "#29323c",
    });
  };

  return (
    <IonItem button color="primary" detail={false} onClick={() => openUrl(url)}>
      <IonThumbnail slot="start">
        <IonImg style={{ backgroundColor: 'white' }} className={`${isImageLoaded && 'fade-in'}`} src={image} alt={title} onIonImgDidLoad={onImageLoaded} />
      </IonThumbnail>
      <IonLabel className="ion-text-wrap">
        <h2 className="bold line-clamp-2">{title}</h2>
        <p className="bold text-md mt-xs">
          {source} | <FormattedDate value={new Date(published * 1000)} year="2-digit" month="short" day="numeric" hour="numeric" minute="2-digit" />
        </p>
      </IonLabel>
    </IonItem>
  )
}

export default PostItem;

// apps/vue/src/components/PostItem.vue
<template>
  <ion-item button :detail="false" color="primary" @click="openUrl(post.url)">
    <ion-thumbnail slot="start">
      <ion-img :src="post.imageurl" :alt="post.title"></ion-img>
    </ion-thumbnail>
    <ion-label class="ion-text-wrap">
      <h2 class="bold line-clamp-2">{{ post.title }}</h2>
      <p class="bold text-md mt-xs">
        {{ post.source_info.name }} |
        {{
          $formatDate(post.published_on * 1000, {
            month: "short",
            day: "numeric",
            year: "2-digit",
            hour: "numeric",
            minute: "2-digit",
          })
        }}
      </p>
    </ion-label>
  </ion-item>
</template>

<script lang="ts">
import { IonImg, IonThumbnail, IonItem, IonLabel } from "@ionic/vue";
import { Browser } from "@capacitor/browser";
import { PropType } from "vue";
import { PostModel } from "@/models/PostModel";

export default {
  name: "PostItem",
  components: {
    IonImg,
    IonThumbnail,
    IonItem,
    IonLabel,
  },
  props: {
    post: {
      type: Object as PropType<PostModel>,
      required: true,
    },
  },
  setup() {
    const openUrl = (url: string) => {
      Browser.open({
        url: url,
        windowName: "_target",
        toolbarColor: "#29323c",
      });
    };

    return { openUrl };
  },
};
</script>

<style lang="scss" scoped>
ion-item {
  p {
    color: var(--ion-color-medium-tint) !important;
  }
}
</style>
